// Generated by design/tokens_tool.py; edit design/tokens.json instead.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "navy": {
          "50": "#f0f1f8",
          "100": "#d9dbed",
          "200": "#b3b7db",
          "300": "#8d93c9",
          "400": "#676fb7",
          "500": "#4a5296",
          "600": "#3a4178",
          "700": "#2b315a",
          "800": "#1e1e50",
          "900": "#1a1a40",
          "950": "#111130"
        },
        "brand": {
          "DEFAULT": "#1e1e50",
          "light": "#2b315a",
          "dark": "#141438"
        }
      },
      "borderRadius": {
        "xs": "5px",
        "sm": "8px",
        "md": "10px",
        "lg": "16px",
        "full": "999px"
      },
      "spacing": {
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px"
      },
      "fontSize": {
        "xs": "12px",
        "sm": "13px",
        "base": "14px",
        "md": "16px",
        "lg": "20px",
        "xl": "28px"
      },
      "fontFamily": {
        "sans": [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ]
      }
    }
  }
};
