"""Per-PR path allowance for the Yozora S1 design-system slice."""

YOZORA_S1_PATHS = (
    "app/database.py",
    "app/template_config.py",
    "app/templates/base.html",
    "app/static/css/style.css",
    "app/static/css/src/fonts.css",
    "app/static/css/src/shell.css",
    "app/static/css/yozora-tokens.css",
    "app/static/css/yozora-components.css",
    "app/static/css/yozora-patterns.css",
    "app/static/fonts/Inter-Medium.woff2",
    "app/static/fonts/Inter-Regular.woff2",
    "app/static/fonts/Inter-SemiBold.woff2",
    "app/static/fonts/OFL-Inter.txt",
    "app/static/fonts/README.md",
    "app/static/vendor/htmx-2.0.4.min.js",
    "design/tokens.json",
    "design/tokens_tool.py",
    "design/yozora-tokens.css",
    "design/yozora-components.css",
    "design/yozora-patterns.css",
    "design/harness/screenshot.py",
    "design/harness/README.md",
    "docs/product/yozora-design-system.md",
    "requirements-dev.txt",
    "tailwind.config.js",
    "tailwind.tokens.cjs",
    "tasks/todo.md",
    "tests/design_lint_allowlist.txt",
    "tests/test_design_lint.py",
    "tests/test_p6_0c_dev_hygiene.py",  # dev-requirements pin gained the S1 visual-harness packages
    "tests/test_design_tokens_in_sync.py",
    "tests/test_design_harness.py",
    "tests/test_white_label.py",
    "tests/test_yozora_shell.py",
    "tests/visual/test_shell_visual.py",
    "tests/visual/test_design_gallery_visual.py",
    "tests/yozora_paths.py",
)

YOZORA_S2_PATHS = (
    "app/config.py",
    "app/main.py",
    "app/routers/design.py",
    "app/static/css/yozora-components.css",
    "app/static/css/yozora-patterns.css",
    "app/static/css/yozora-tokens.css",
    "app/templates/components/engagement_status_badge.html",
    "app/templates/components/evidence_status_badge.html",
    "app/templates/components/layout.html",
    "app/templates/components/status_badge.html",
    "app/templates/components/ui.html",
    "app/templates/pages/design.html",
    "tailwind.tokens.cjs",
    "tasks/handoffs/2026-10-01-yozora-s2-handoff.md",
    "tasks/todo.md",
    "tests/design_lint_allowlist.txt",
    "tests/test_design_lint.py",
    "tests/test_yozora_s2.py",
    "tests/p6_10_support.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_3a_grounding.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_7_requirement_card.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_7b_add_to_rfi.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_8_b2_docx_xlsx.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_8_board_report_v2.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_8_v3a_data_capture.py",  # Yozora per-PR allowance (guard file)
    "tests/test_p6_9_file_set.py",  # Yozora per-PR allowance (guard file)
    "tests/test_retention.py",  # Yozora per-PR allowance (guard file)
    "tests/yozora_paths.py",
)

YOZORA_S4_PATHS = (
    "docs/product/yozora-migration-map.md",
    "app/routers/web.py",
    "app/routers/retention.py",
    "app/template_config.py",
    "app/templates/pages/engagement_detail.html",
    "app/templates/pages/engagement_purge.html",
    "app/templates/pages/engagements.html",
    "app/templates/pages/integrated_reports.html",
    "app/templates/pages/assessment.html",
    "app/templates/pages/new_assessment.html",
    "app/templates/pages/new_engagement.html",
    "app/templates/pages/reports.html",
    "app/templates/pages/remediation_tracker.html",
    "app/templates/partials/client_picker.html",
    "app/templates/partials/engagement_list.html",
    "app/templates/partials/engagement_retention.html",
    "app/templates/partials/yozora_page_controls.html",
    "design/harness/seed_s4.py",
    "tasks/handoffs/2026-10-01-yozora-s4-handoff.md",
    "tasks/todo.md",
    "tests/test_yozora_shell.py",
    "tests/test_yozora_add_assessment.py",
    "tests/test_yozora_s4.py",
    "tests/test_retention.py",
)

YOZORA_S6_PATHS = (
    "app/routers/design.py",
    "app/routers/evidence_reuse.py",
    "app/routers/requirement_review.py",
    "app/routers/web.py",
    "app/template_config.py",
    "app/templates/components/evidence_status_badge.html",
    "app/templates/components/ui.html",
    "app/templates/components/workpaper_entry.html",
    "app/templates/pages/aws_evidence.html",
    "app/templates/pages/evidence_detail.html",
    "app/templates/pages/evidence_inventory.html",
    "app/templates/pages/evidence_reuse.html",
    "app/templates/pages/evidence_span.html",
    "app/templates/pages/workpaper.html",
    "app/templates/partials/aws_evidence_panel.html",
    "app/templates/partials/document_list.html",
    "app/templates/partials/documents_tab.html",
    "app/templates/partials/upload_status.html",
    "design/harness/seed_s6.py",
    "docs/product/yozora-migration-map.md",
    "tasks/handoffs/2026-10-01-yozora-s6-handoff.md",
    "tasks/todo.md",
    "tests/test_longitudinal_demo.py",
    "tests/test_design_lint.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_p6_7b_add_to_rfi.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_evidence_service.py",
    "tests/test_workpaper.py",
    "tests/p6_10_support.py",
    "tests/test_yozora_s6.py",
    "tests/visual/test_shell_visual.py",
    "tests/yozora_paths.py",
)

YOZORA_S3_PATHS = (
    "app/routers/design.py",
    "app/routers/firm_settings.py",
    "app/routers/web.py",
    "app/services/firm_settings.py",
    "app/services/portfolio.py",
    "app/services/request_summary.py",
    "app/services/retention.py",
    "app/static/css/yozora-patterns.css",
    "app/template_config.py",
    "app/templates/base.html",
    "app/templates/components/layout.html",
    "app/templates/components/ui.html",
    "app/templates/pages/client_detail.html",
    "app/templates/pages/clients.html",
    "app/templates/pages/dashboard.html",
    "app/templates/pages/firm_settings.html",
    "app/templates/pages/login.html",
    "app/templates/pages/review.html",
    "design/harness/seed_s3.py",
    "docs/product/yozora-migration-map.md",
    "tasks/handoffs/2026-10-01-yozora-s3-handoff.md",
    "tasks/todo.md",
    "tests/test_yozora_s3.py",
    "tests/test_yozora_firm_settings.py",
    "tests/test_yozora_shell.py",
    "tests/design_lint_allowlist.txt",
    "tests/p6_10_support.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_7b_add_to_rfi.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_retention.py",
    "tests/test_longitudinal_demo.py",
    "tests/test_p5_2_reader_migration.py",
    "tests/visual/test_shell_visual.py",
    "tests/yozora_paths.py",
)

# Yozora per-PR allowance.
YOZORA_S5_PATHS = (
    "app/static/js/app.js",  # s5-quest: save indicator fires on saves only
    "app/services/screening.py",  # s5 review: SCREENING_UNAVAILABLE_COPY constant (copy only)
    "app/routers/web.py",
    "app/static/css/yozora-patterns.css",
    "app/templates/components/layout.html",
    "app/templates/components/engagement_status_badge.html",
    "app/templates/components/status_badge.html",
    "app/templates/pages/assessment.html",
    "app/templates/partials/assessment_header.html",
    "app/templates/partials/analysis_running.html",
    "app/templates/partials/context_complete.html",
    "app/templates/partials/desk_review_error.html",
    "app/templates/partials/desk_review_findings.html",
    "app/templates/partials/desk_review_ready.html",
    "app/templates/partials/desk_review_running.html",
    "app/templates/partials/followup_questions.html",
    "app/templates/partials/framework_tabs.html",
    "app/templates/partials/question_step.html",
    "app/templates/partials/questionnaire_sections.html",
    "app/templates/partials/questionnaire_tab.html",
    "app/templates/partials/scope_complete.html",
    "app/templates/partials/scope_form.html",
    "app/templates/partials/scope_tab.html",
    "app/templates/partials/screening_form.html",
    "app/templates/partials/section_questions.html",
    "app/templates/partials/section_saved.html",
    "app/templates/partials/status_timeline.html",
    "design/harness/seed_s5.py",
    "docs/product/yozora-migration-map.md",
    "tasks/handoffs/2026-10-01-yozora-s5-handoff.md",
    "tasks/handoffs/2026-10-04-yozora-s5-s6-orchestration.md",
    "tasks/todo.md",
    "tests/test_p5_4_adaptive_ucc_questionnaire.py",
    "tests/test_report_snapshots.py",
    "tests/test_retention.py",
    "tests/test_p5_5_scoping_evidence.py",
    "tests/p6_10_support.py",
    "tests/test_longitudinal_demo.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_7b_add_to_rfi.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_yozora_s5.py",
    "app/templates/pages/design_assessment_preview.html",
    "app/templates/partials/analysis_complete.html",
    "app/templates/partials/analysis_error.html",
    "app/templates/partials/desk_review_prefilling.html",
    "app/templates/pages/desk_review.html",  # s5-b4: live b4 "Pre-fill from documents" page
    "app/templates/partials/framework_hub_panel.html",
    "tests/test_p5_3_framework_desk_review.py",
    "tests/test_picker_and_scoring_contract.py",
    "tests/yozora_paths.py",
)

YOZORA_DESIGN_FILES = (
    "design/tokens.json",
    "design/tokens_tool.py",
    "design/yozora-components.css",
    "design/yozora-patterns.css",
    "design/yozora-tokens.css",
    "design/harness",
    "docs/product/yozora-design-system.md",
    "docs/product/2026-10-01-app-design-mockups",
    "tasks/handoffs/2026-10-01-yozora-s1-handoff.md",
)

# Yozora per-PR allowance: S7 analysis, review, report, narrative and board inputs.
YOZORA_S7_PATHS = (
    "app/routers/design.py",
    "app/routers/design_s7_analysis.py",
    "app/routers/design_s7_cards.py",
    "app/routers/design_s7_findings.py",
    "app/routers/design_s7_narrative.py",
    "app/routers/design_s7_pages.py",
    "app/routers/design_s7_report.py",
    "app/routers/drafting.py",
    "tests/test_findings.py",  # Yozora per-PR allowance (guard file)
    "app/routers/requirement_review.py",  # Yozora per-PR allowance (engagement crumb context)
    "app/static/css/yozora-patterns.css",
    "app/templates/components/conclusion_card.html",
    "app/templates/components/finding_card.html",
    "app/templates/components/requirement_card_body.html",
    "app/templates/components/seg_rows.html",
    "app/templates/pages/board_inputs.html",
    "app/templates/pages/conclusions.html",
    "app/templates/pages/findings.html",
    "app/templates/pages/narrative.html",
    "app/templates/pages/review_queue.html",
    "app/templates/partials/analysis_complete.html",
    "app/templates/partials/analysis_error.html",
    "app/templates/partials/analysis_gate_blocked.html",
    "app/templates/partials/analysis_running.html",
    "app/templates/partials/framework_panel.html",
    "app/templates/partials/no_report.html",
    "app/templates/partials/release_panel.html",
    "app/templates/partials/remediation_draft.html",
    "app/templates/partials/remediation_panel.html",
    "app/templates/partials/remediation_summary.html",
    "app/templates/partials/report_basis_panel.html",
    "app/templates/partials/report_summary.html",
    "app/templates/partials/report_tab.html",
    "app/templates/partials/review_finding_card.html",
    "tasks/handoffs/2026-10-04-yozora-s7-orchestration.md",
    "tasks/handoffs/2026-10-05-yozora-s7-codex-handoff.md",
    "tasks/handoffs/2026-10-05-yozora-s7-fix-pass.md",
    "tasks/handoffs/s7-wip/analysis.patch",
    "tasks/handoffs/s7-wip/cards.patch",
    "tasks/handoffs/s7-wip/findings.patch",
    "tasks/handoffs/s7-wip/narrative.patch",
    "tasks/handoffs/s7-wip/pages.patch",
    "tasks/handoffs/s7-wip/report.patch",
    "tasks/todo.md",
    "tests/test_needs_review_ui.py",
    "tests/test_picker_and_scoring_contract.py",
    "tests/test_remediation_tracking.py",
    "tests/test_yozora_s7_analysis.py",
    "tests/test_yozora_s7_cards.py",
    "tests/test_yozora_s7_findings.py",
    "tests/test_yozora_s7_narrative.py",
    "tests/test_yozora_s7_report.py",
    "tests/yozora_paths.py",
)

# Guard-only allowance: this existing path guard was updated to recognize S7.
# It is intentionally separate from the S7 product-test paths.
YOZORA_S7_GUARD_PATHS = (
    "tests/test_p6_4_cap_upload_limit.py",
    # V3-C3 XLSX parity: scoped per-PR allowances in existing file-set guards.
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_p6_8_v3b_file_set.py",
    "tests/test_p6_2b_dpdpa_criteria.py",
)

# Yozora per-PR allowance (S8 scaffold and planned slice files).
YOZORA_S8_PATHS = (
    "app/routers/design.py",
    "app/routers/design_s8_requests.py",
    "app/routers/design_s8_versions.py",
    "app/routers/design_s8_client.py",
    "app/routers/magic.py",
    "app/routers/snapshots.py",
    "app/routers/soa.py",
    "app/routers/web.py",
    "app/templates/magic/invalid.html",
    "app/templates/magic/upload.html",
    "app/templates/pages/comparison.html",
    "app/templates/pages/report_snapshots.html",
    "app/templates/pages/rfi.html",
    "app/templates/pages/soa.html",
    "app/templates/pages/requests.html",
    "app/templates/partials/magic_links.html",
    "app/templates/partials/rfi_links.html",
    "app/static/js/magic-client.js",
    "design/harness/gate_s8.py",
    "design/harness/seed_s8.py",
    "design/harness/seed_s8_requests.py",
    "design/harness/seed_s8_versions.py",
    "design/harness/seed_s8_client.py",
    "tasks/handoffs/2026-10-01-yozora-s8-handoff.md",
    "tasks/handoffs/2026-10-05-yozora-s8-a-requests.md",
    "tasks/handoffs/2026-10-05-yozora-s8-b-versions.md",
    "tasks/handoffs/2026-10-05-yozora-s8-c-client.md",
    "tasks/handoffs/2026-10-05-yozora-s8-codex-orchestration.md",
    "tasks/handoffs/2026-10-05-yozora-s8-orchestration.md",
    "tasks/handoffs/2026-10-06-yozora-s8-fix-pass.md",
    "tasks/todo.md",
    "tests/test_design_lint.py",
    "tests/test_aws_evidence.py",
    "tests/test_longitudinal_demo.py",
    "tests/test_magic_links.py",
    "tests/test_p5_6_rfi_rebuild.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_retention.py",
    "tests/test_yozora_magic_link_contacts.py",
    "tests/test_yozora_s4.py",
    "tests/test_yozora_s5.py",
    "tests/test_p6_2b_dpdpa_criteria.py",
    "tests/test_longitudinal_demo.py",
    "tests/p6_10_support.py",
    "tests/test_p6_10a_remediation_draft.py",
    "tests/test_p6_10b_narrative.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_7b_add_to_rfi.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_retention.py",
    "tests/test_yozora_s8_requests.py",
    "tests/test_yozora_s8_versions.py",
    "tests/test_yozora_s8_client.py",
    "tests/test_magic_links.py",
    "tests/test_yozora_magic_link_contacts.py",
    "tests/yozora_paths.py",
)

# Yozora per-PR allowance (S9 scaffold and planned slice files).
YOZORA_S9_PATHS = (
    "app/main.py",
    "app/routers/design.py",
    "app/routers/design_s9_errors.py",
    "app/routers/design_s9_system.py",
    "app/static/css/yozora-components.css",
    "app/static/css/yozora-patterns.css",
    "app/static/css/tailwind.css",
    "app/static/css/style.css",
    "app/static/js/app.js",
    "app/static/css/input.css",
    "app/templates/base.html",
    "app/templates/components/ui.html",
    "app/templates/pages/design.html",
    "app/templates/pages/design_s9_system.html",
    "app/templates/partials/yozora_page_controls.html",
    "app/templates/pages/error.html",
    "app/templates/pages/assessment.html",
    "app/templates/pages/clients.html",
    "app/templates/pages/evidence_reuse.html",
    "app/templates/pages/integrated_reports.html",
    "app/templates/partials/client_picker.html",
    "app/templates/partials/context_complete.html",
    "app/templates/partials/followup_questions.html",
    "app/templates/partials/questionnaire_sections.html",
    "app/templates/partials/questionnaire_tab.html",
    "app/templates/partials/scope_complete.html",
    "app/templates/partials/scope_form.html",
    "app/templates/partials/section_questions.html",
    "design/harness/gate_s9.py",
    "design/harness/seed_s9.py",
    "design/harness/seed_s9_errors.py",
    "design/harness/seed_s9_system.py",
    "design/yozora-components.css",
    "design/yozora-patterns.css",
    "docs/product/yozora-migration-map.md",
    "package.json",
    "package-lock.json",
    "tailwind.tokens.cjs",
    "tailwind.config.js",
    "tasks/handoffs/2026-10-06-yozora-s9-orchestration.md",
    "tasks/handoffs/2026-10-06-yozora-s9-fix-pass.md",
    ".gitignore",
    "tasks/handoffs/2026-10-06-yozora-s9-a-errors.md",
    "tasks/handoffs/2026-10-06-yozora-s9-b-system.md",
    "tasks/handoffs/2026-10-06-yozora-s9-c-cleanup.md",
    "tasks/todo.md",
    "tests/design_lint_allowlist.txt",
    "tests/test_design_tokens_in_sync.py",
    "tests/p6_10_support.py",
    "tests/test_design_lint.py",
    "tests/test_longitudinal_demo.py",
    "tests/test_p6_2b_dpdpa_criteria.py",
    "tests/test_p6_4_cap_upload_limit.py",
    "tests/test_p6_4_whats_missing.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_7b_add_to_rfi.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_retention.py",
    "tests/test_yozora_s9_cleanup.py",
    "tests/test_yozora_s9_errors.py",
    "tests/test_yozora_s9_system.py",
    "tests/yozora_paths.py",
)

# Per-PR allowance: V3-C board deck design pass (mockup, scope, dumbbell backend handoff).
V3C_MOCKUP_PATHS = (
    "docs/product/2026-10-04-board-deck-v3c-mockup/deck_template.html",
    "docs/product/2026-10-04-board-deck-v3c-mockup/render_deck.py",
    "docs/product/2026-10-04-board-deck-v3c-mockup/deck.pdf",
    "docs/product/2026-10-04-board-deck-v3c-mockup/deck-sparse.pdf",
    "tasks/2026-10-04-deliverables-quality-scope.md",
    "tasks/handoffs/2026-10-04-v3c-prior-domain-scores.md",
    "tests/test_p6_8_v3b_file_set.py",
)

# Per-PR allowance: RFI and Requests consolidation (tasks/2026-10-06-rfi-requests-consolidation.md).
RFI_REQUESTS_PATHS = (
    "app/routers/firm_settings.py",
    "app/routers/magic.py",
    "app/routers/retention.py",
    "app/routers/snapshots.py",
    "app/services/rfi_requests.py",
    "app/static/js/app.js",
    "app/templates/pages/assessment.html",
    "app/templates/pages/engagement_detail.html",
    "app/templates/pages/engagement_purge.html",
    "app/templates/pages/firm_settings.html",
    "app/templates/pages/requests.html",
    "app/templates/pages/rfi.html",
    "app/templates/partials/document_list.html",
    "app/templates/partials/engagement_retention.html",
    "app/templates/partials/magic_links.html",
    "app/templates/partials/rfi_links.html",
    "app/templates/partials/scope_complete.html",
    "docs/product/yozora-design-system.md",
    "docs/product/yozora-migration-map.md",
    "tasks/2026-10-06-rfi-requests-consolidation.md",
    "tasks/2026-10-06-status-log.md",
    "tasks/handoffs/2026-10-06-rfi-requests-cloud-kickoff.md",
    "tests/p6_10_support.py",
    "tests/test_longitudinal_demo.py",
    "tests/test_magic_links.py",
    "tests/test_p6_2b_dpdpa_criteria.py",
    "tests/test_p6_7_requirement_card.py",
    "tests/test_p6_7b_add_to_rfi.py",
    "tests/test_p6_8_b2_docx_xlsx.py",
    "tests/test_p6_8_board_report_v2.py",
    "tests/test_p6_8_v3a_data_capture.py",
    "tests/test_p6_9_file_set.py",
    "tests/test_requests_hub.py",
    "tests/test_retention.py",
    "tests/test_rfi_link_picker.py",
    "tests/test_scope_complete_layout.py",
    "tests/test_settings_archive.py",
    "tests/test_yozora_firm_settings.py",
    "tests/test_yozora_s4.py",
    "tests/test_yozora_s5.py",
    "tests/yozora_paths.py",
)

YOZORA_ALL_PATHS = YOZORA_S1_PATHS + YOZORA_S2_PATHS + YOZORA_S3_PATHS + YOZORA_S4_PATHS + YOZORA_S5_PATHS + YOZORA_S6_PATHS + YOZORA_S7_PATHS + YOZORA_S8_PATHS + YOZORA_S9_PATHS + YOZORA_DESIGN_FILES + V3C_MOCKUP_PATHS + RFI_REQUESTS_PATHS
YOZORA_EXCLUDES = [f":(exclude){path}" for path in YOZORA_ALL_PATHS]
