"""P1-2: add client/engagement/evidence/conclusion hierarchy tables

Revision ID: 5c7c75960f43
Revises: 6fcd9e575309
Create Date: 2026-09-22 18:03:47.106580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7c75960f43'
down_revision: Union[str, None] = '6fcd9e575309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('engagements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_client_id'), ['client_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('magic_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('scope_json', sa.Text(), nullable=False),
    sa.Column('max_uploads', sa.Integer(), nullable=False),
    sa.Column('max_size_bytes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('claims_json', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('assessment_packs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('pack_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_packs_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('conclusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('gaps_identified', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('ai_proposed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conclusions_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('evidence_uses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('relevance', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_uses_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_uses_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('evidence_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_versions_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('report_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_issued', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_snapshots_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_snapshots_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_version_id', sa.String(length=36), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('location_ref', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_version_id'], ['evidence_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_evidence_version_id'), ['evidence_version_id'], unique=False)

    op.create_table('conclusion_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conclusion_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('previous_outcome', sa.String(length=40), nullable=True),
    sa.Column('previous_rationale', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conclusion_id'], ['conclusions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conclusion_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conclusion_revisions_conclusion_id'), ['conclusion_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('conclusion_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['conclusion_id'], ['conclusions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_conclusion_id'), ['conclusion_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_finding_id'), ['finding_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_id', sa.String(length=36), nullable=True))
        # Existing assessments may already have rows. The temporary server
        # default lets this nullable-safe schema change succeed before P1-3
        # backfills and later tightens the application invariant.
        batch_op.add_column(
            sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False)
        )
        batch_op.create_index(batch_op.f('ix_assessments_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_assessments_engagement_id_engagements',
            'engagements',
            ['engagement_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessments_engagement_id_engagements', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assessments_engagement_id'))
        batch_op.drop_column('version')
        batch_op.drop_column('engagement_id')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_finding_id'))

    op.drop_table('actions')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_conclusion_id'))
        batch_op.drop_index(batch_op.f('ix_findings_assessment_id'))

    op.drop_table('findings')
    with op.batch_alter_table('conclusion_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conclusion_revisions_conclusion_id'))

    op.drop_table('conclusion_revisions')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_evidence_version_id'))

    op.drop_table('citations')
    with op.batch_alter_table('report_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_snapshots_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_report_snapshots_assessment_id'))

    op.drop_table('report_snapshots')
    with op.batch_alter_table('evidence_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_versions_evidence_id'))

    op.drop_table('evidence_versions')
    with op.batch_alter_table('evidence_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_uses_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_uses_assessment_id'))

    op.drop_table('evidence_uses')
    with op.batch_alter_table('conclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conclusions_assessment_id'))

    op.drop_table('conclusions')
    with op.batch_alter_table('assessment_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_packs_assessment_id'))

    op.drop_table('assessment_packs')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_assessment_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_engagement_id'))

    op.drop_table('magic_links')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_engagement_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_client_id'))

    op.drop_table('engagements')
    op.drop_table('clients')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
