"""Build the checked-in application token outputs from ``design/tokens.json``.

``tokens.json`` is the source of truth.  ``check`` renders every generated
artifact in memory and exits non-zero when any checked-in copy has drifted.
"""

from __future__ import annotations

import json
import pathlib
import sys
from collections.abc import Mapping


DESIGN_DIR = pathlib.Path(__file__).parent
REPO_ROOT = DESIGN_DIR.parent
TOKENS_PATH = DESIGN_DIR / "tokens.json"
STATIC_CSS_DIR = REPO_ROOT / "app" / "static" / "css"


def load_tokens() -> dict[str, dict[str, str]]:
    raw = json.loads(TOKENS_PATH.read_text())
    if not isinstance(raw, dict) or not all(isinstance(value, dict) for value in raw.values()):
        raise ValueError("tokens.json must contain selector-to-token mappings")
    return raw


def render_css(tokens: Mapping[str, Mapping[str, str]]) -> str:
    """Render CSS selectors in JSON insertion order.

    ``:tailwind`` is metadata for the legacy Tailwind build and is deliberately
    not emitted as CSS.
    """
    blocks = []
    for selector, values in tokens.items():
        if selector == ":tailwind":
            continue
        declarations = "\n".join(f"  {name}: {value};" for name, value in values.items())
        blocks.append(f"{selector} {{\n{declarations}\n}}")
    return "\n\n".join(blocks) + "\n"


def _tailwind_value(tokens: Mapping[str, str], name: str) -> str:
    try:
        return tokens[name]
    except KeyError as exc:
        raise ValueError(f"missing Tailwind token {name}") from exc


def render_tailwind(tokens: Mapping[str, Mapping[str, str]]) -> str:
    metadata = tokens.get(":tailwind", {})
    navy = {
        key.removeprefix("--navy-"): value
        for key, value in metadata.items()
        if key.startswith("--navy-")
    }
    brand = {
        "DEFAULT": _tailwind_value(metadata, "--brand"),
        "light": _tailwind_value(metadata, "--brand-light"),
        "dark": _tailwind_value(metadata, "--brand-dark"),
    }
    root = tokens.get(":root", {})
    radius = {
        key.removeprefix("--r-"): value
        for key, value in root.items()
        if key.startswith("--r-")
    }
    spacing = {
        key.removeprefix("--s-"): value
        for key, value in root.items()
        if key.startswith("--s-")
    }
    font_size = {
        key.removeprefix("--t-"): value
        for key, value in root.items()
        if key.startswith("--t-")
    }

    generated = {
        "theme": {
            "extend": {
                "colors": {"navy": navy, "brand": brand},
                "borderRadius": radius,
                "spacing": spacing,
                "fontSize": font_size,
                "fontFamily": {
                    "sans": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"]
                },
            }
        }
    }
    return "// Generated by design/tokens_tool.py; edit design/tokens.json instead.\nmodule.exports = " + json.dumps(generated, indent=2) + ";\n"


def generated_files() -> dict[pathlib.Path, str]:
    tokens = load_tokens()
    return {
        STATIC_CSS_DIR / "yozora-tokens.css": render_css(tokens),
        REPO_ROOT / "tailwind.tokens.cjs": render_tailwind(tokens),
        STATIC_CSS_DIR / "yozora-components.css": (DESIGN_DIR / "yozora-components.css").read_text(),
        STATIC_CSS_DIR / "yozora-patterns.css": (DESIGN_DIR / "yozora-patterns.css").read_text(),
    }


def check() -> int:
    drift = []
    for path, expected in generated_files().items():
        if not path.exists() or path.read_text() != expected:
            drift.append(str(path.relative_to(REPO_ROOT)))
    if drift:
        print("DRIFT in generated design files:")
        print("\n".join(f"- {path}" for path in drift))
        return 1
    print("generated design files match tokens.json")
    return 0


def build() -> int:
    for path, content in generated_files().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print("wrote", path.relative_to(REPO_ROOT))
    return 0


def main(mode: str) -> int:
    if mode in {"build", "write"}:
        return build()
    if mode == "check":
        return check()
    print("Usage: python design/tokens_tool.py build|check", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "check"))
