"""
Unified Control Cluster (UCC) mapping data.

The cluster engine expects a list of cluster definitions. Each definition uses:
  - ``cluster_id``: stable identifier such as ``CLUSTER_001``
  - ``topic``: short human-readable title
  - ``primary_question`` / ``primary_guidance``: merged assessment prompt
  - ``controls``: list of member controls with ``framework`` / ``control`` keys
  - ``delta``: optional framework-specific nuance shown as a follow-up

These mappings intentionally focus first on the highest-overlap areas across
DPDPA, ISO 27001, and GDPR so multi-framework questionnaires de-duplicate the
largest shared control families before falling back to singletons.
"""

from __future__ import annotations


def _control(
    framework: str,
    control: str,
    delta: str | None = None,
) -> dict[str, str]:
    item = {"framework": framework, "control": control}
    if delta:
        item["delta"] = delta
    return item


def _cluster(
    cluster_id: str,
    topic: str,
    question: str,
    guidance: str,
    controls: list[dict[str, str]],
    *,
    tags: list[str],
    criticality: str = "high",
    domain_group: str,
) -> dict[str, object]:
    return {
        "cluster_id": cluster_id,
        "topic": topic,
        "tags": tags,
        "primary_question": question,
        "primary_guidance": guidance,
        "controls": controls,
        "criticality": criticality,
        "domain_group": domain_group,
    }


CONTROL_CLUSTERS: list[dict[str, object]] = [
    _cluster(
        "CLUSTER_001",
        "Governance Framework And Policy Accountability",
        "Does your organization maintain a documented privacy and information security governance framework, approved by leadership and reviewed on a defined cadence?",
        "Look for board or management approval, named policy owners, review dates, implementation accountability, and evidence that the framework is communicated and enforced.",
        [
            _control("iso27001", "ISO.A5.1"),
            _control("iso27001", "ISO.A5.4"),
            _control("gdpr", "GDPR.ART24.1"),
            _control("gdpr", "GDPR.ART24.2"),
            _control("gdpr", "GDPR.ART5.1"),
            _control("nist_csf", "NIST.GV.OC.03", "NIST expects governance decisions to reflect legal and regulatory requirements."),
            _control("nist_csf", "NIST.GV.RM.01", "NIST expects documented risk management objectives at the organizational level."),
            _control("nist_csf", "NIST.GV.RM.02", "NIST also expects an articulated risk appetite and tolerance."),
            _control("nist_csf", "NIST.GV.RR.01", "NIST expects organizational leadership to be accountable for cybersecurity risk."),
            _control("nist_csf", "NIST.GV.PO.01", "NIST requires a documented cybersecurity policy."),
            _control("nist_csf", "NIST.GV.PO.02", "NIST also expects the policy to be reviewed and updated."),
            _control("pci_dss", "PCI.12.1", "PCI DSS requires a comprehensive information security policy."),
            _control("hipaa", "HIPAA.164.308a1iii", "HIPAA expects a sanction policy for workforce members who fail to comply."),
            _control("iso27001", "ISO.A5.31", "ISO expects legal, statutory, regulatory, and contractual requirements to be identified and complied with."),
            _control("iso27001", "ISO.A5.37", "ISO expects documented operating procedures for information processing."),
        ],
        tags=['governance', 'policy', 'management-commitment', 'accountability'],
        criticality="critical",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_002",
        "DPO And Assigned Privacy Responsibilities",
        "Has the organization formally assigned privacy and security responsibilities, including an empowered DPO or equivalent role where required?",
        "Look for an appointment record, role description, independence, reporting line, and evidence that the function is engaged in ongoing oversight rather than acting only on paper.",
        [
            _control("dpdpa", "CH4.SDF.1", "DPDPA focuses on DPO appointment for Significant Data Fiduciaries."),
            _control("iso27001", "ISO.A5.2", "ISO expects defined and allocated information security roles across the organization."),
            _control("gdpr", "GDPR.ART37.1", "GDPR requires documented criteria and designation of a DPO where Art 37 applies."),
            _control("gdpr", "GDPR.ART38.1", "GDPR also requires independence, access to management, and no conflict of interest."),
            _control("gdpr", "GDPR.ART39.1", "GDPR specifies advisory, monitoring, and supervisory authority liaison tasks."),
            _control("nist_csf", "NIST.GV.RR.02", "NIST expects cybersecurity roles and responsibilities to be established and communicated."),
            _control("nist_csf", "NIST.GV.RR.03", "NIST also expects adequate resourcing for the assigned cybersecurity function."),
        ],
        tags=['governance', 'dpo', 'roles-responsibilities', 'organizational-structure'],
        criticality="critical",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_003",
        "Privacy By Design And DPIA Governance",
        "Does the organization assess privacy risk during design and delivery of new processing activities, including conducting DPIAs where high-risk processing is identified?",
        "Look for project gates, DPIA criteria, completed assessments, risk treatment decisions, and evidence that privacy-by-design controls are embedded in delivery workflows.",
        [
            _control("dpdpa", "CH4.SDF.3", "DPDPA emphasizes DPIAs for Significant Data Fiduciaries."),
            _control("iso27001", "ISO.A5.8", "ISO expects security to be integrated into project management."),
            _control("gdpr", "GDPR.ART35.1", "GDPR requires a documented DPIA process for high-risk processing."),
            _control("gdpr", "GDPR.ART35.2", "GDPR also expects clear criteria to determine when a DPIA is triggered."),
            _control("gdpr", "GDPR.ART25.1", "GDPR requires data protection by design in system and process design choices."),
            _control("gdpr", "GDPR.ART25.2", "GDPR also requires data protection by default settings and configurations."),
            _control("nist_csf", "NIST.GV.OC.04", "NIST expects critical objectives and dependencies to be understood before processing changes."),
            _control("nist_csf", "NIST.GV.OV.01", "NIST expects the risk management strategy to be reviewed against organizational risk decisions."),
            _control("gdpr", "GDPR.ART36.1", "GDPR requires prior consultation with the supervisory authority when a DPIA indicates high residual risk."),
        ],
        tags=['governance', 'dpia', 'privacy-by-design', 'risk-assessment'],
        criticality="critical",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_004",
        "Independent Review And Assurance",
        "Does the organization perform independent assurance over its privacy and security control environment on a recurring basis?",
        "Look for audit plans, external or independent review reports, remediation tracking, and evidence that findings reach accountable leadership.",
        [
            _control("dpdpa", "CH4.SDF.2", "DPDPA requires an Independent Data Auditor for Significant Data Fiduciaries."),
            _control("dpdpa", "CH4.SDF.4", "DPDPA also expects periodic audits to be completed."),
            _control("iso27001", "ISO.A5.35", "ISO requires independent review of information security."),
            _control("gdpr", "GDPR.ART32.4", "GDPR expects testing and evaluation of security measures as part of ongoing assurance."),
            _control("hipaa", "HIPAA.164.308a8", "HIPAA requires periodic technical and non-technical security evaluation."),
            _control("pci_dss", "PCI.12.4", "PCI DSS requires ongoing management of PCI DSS compliance."),
            _control("iso27001", "ISO.A5.36", "ISO expects compliance with security policies, rules, and standards to be monitored and reviewed."),
            _control("iso27001", "ISO.A8.34", "ISO expects protection of information systems during audit testing to avoid disruption."),
        ],
        tags=['governance', 'audit', 'independent-review', 'compliance-audit'],
        criticality="high",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_005",
        "Processing Inventory And Accountability Records",
        "Does the organization maintain an up-to-date inventory of processing activities, systems, and data assets that supports privacy and security governance?",
        "Look for a maintained asset or processing register, ownership assignments, system scope, and evidence that records are updated when processing changes.",
        [
            _control("iso27001", "ISO.A5.9"),
            _control("gdpr", "GDPR.ART30.1", "GDPR expects a controller record of processing activities."),
            _control("gdpr", "GDPR.ART30.2", "GDPR expects processor-side records where the organization acts as a processor."),
            _control("nist_csf", "NIST.ID.AM.01", "NIST expects a maintained inventory of hardware assets."),
            _control("nist_csf", "NIST.ID.AM.02", "NIST also expects a maintained inventory of software and services."),
            _control("nist_csf", "NIST.ID.AM.03", "NIST expects network communication and data flows to be mapped."),
            _control("nist_csf", "NIST.ID.AM.04", "NIST expects external systems and services to be inventoried."),
            _control("nist_csf", "NIST.ID.AM.05", "NIST expects assets to be prioritized based on criticality and sensitivity."),
        ],
        tags=['governance', 'documentation', 'data-inventory', 'records-of-processing'],
        criticality="high",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_006",
        "Access Control Baseline",
        "Are logical access rules defined and enforced so users receive only the access needed for their role and risk profile?",
        "Look for an access control policy, role definitions, approval workflow, least-privilege standards, and evidence that access is technically enforced.",
        [
            _control("dpdpa", "CH2.SECURITY.1", "DPDPA expects reasonable technical and organisational security safeguards for personal data."),
            _control("dpdpa", "CH2.SECURITY.2", "DPDPA emphasizes encryption and access controls for personal data."),
            _control("iso27001", "ISO.A5.15", "ISO requires access control rules based on business and security needs."),
            _control("iso27001", "ISO.A8.3", "ISO also expects information access restriction to be implemented technically."),
            _control("gdpr", "GDPR.ART32.1", "GDPR expects appropriate technical and organisational security measures based on risk."),
            _control("hipaa", "HIPAA.164.312a1", "HIPAA requires unique user identification as a baseline access control."),
            _control("hipaa", "HIPAA.164.308a3i", "HIPAA expects authorization and supervision of workforce members with access to ePHI."),
            _control("nist_csf", "NIST.PR.AA.05", "NIST expects access permissions and authorizations to be defined."),
            _control("nist_csf", "NIST.PR.AA.06", "NIST also expects least privilege to be enforced."),
            _control("pci_dss", "PCI.7.1", "PCI DSS requires defined and understood access control processes."),
            _control("pci_dss", "PCI.7.2", "PCI DSS expects access to system components and data appropriately defined."),
            _control("pci_dss", "PCI.7.3", "PCI DSS expects access managed via a defined access control system."),
            _control("iso27001", "ISO.A6.7", "ISO expects controls for secure remote working and mobile computing."),
        ],
        tags=['security', 'access-control', 'least-privilege', 'authorization'],
        criticality="critical",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_007",
        "Identity Lifecycle And Access Reviews",
        "Does the organization manage identity lifecycle events and review access rights throughout joiner, mover, leaver, and role-change scenarios?",
        "Look for provisioning, modification, recertification, segregation of duties, and timely removal of access when users change roles or depart.",
        [
            _control("iso27001", "ISO.A5.3"),
            _control("iso27001", "ISO.A5.16"),
            _control("iso27001", "ISO.A5.18"),
            _control("hipaa", "HIPAA.164.308a3ii", "HIPAA requires workforce clearance procedures before granting access."),
            _control("hipaa", "HIPAA.164.308a3iii", "HIPAA also requires termination procedures to remove access on departure."),
            _control("hipaa", "HIPAA.164.308a4i", "HIPAA requires policies and procedures for authorizing access."),
            _control("hipaa", "HIPAA.164.308a4ii", "HIPAA also requires access establishment and modification procedures."),
            _control("nist_csf", "NIST.PR.AA.01", "NIST expects identities and credentials to be managed for authorized users and devices."),
            _control("nist_csf", "NIST.PR.AA.02", "NIST also expects identity proofing and binding to a credential."),
            _control("pci_dss", "PCI.7.4", "PCI DSS requires access to be reviewed periodically."),
            _control("iso27001", "ISO.A5.11", "ISO expects return of assets upon termination or change of employment."),
            _control("iso27001", "ISO.A6.5", "ISO expects responsibilities after termination or change of employment to be maintained."),
        ],
        tags=['security', 'identity-management', 'access-review', 'segregation-of-duties'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_008",
        "Authentication And Credential Protection",
        "Are authentication methods and credential handling practices designed to prevent unauthorized access to systems that process personal data?",
        "Look for password standards, MFA, secure credential storage, rotation or recovery controls, and explicit handling guidance for privileged or high-risk accounts.",
        [
            _control("iso27001", "ISO.A5.17"),
            _control("iso27001", "ISO.A8.5"),
            _control("gdpr", "GDPR.ART32.2", "GDPR specifically calls out pseudonymisation and encryption as appropriate measures."),
            _control("hipaa", "HIPAA.164.308a5v", "HIPAA expects password management procedures."),
            _control("hipaa", "HIPAA.164.312a3", "HIPAA expects automatic logoff to limit exposed sessions."),
            _control("nist_csf", "NIST.PR.AA.03", "NIST expects authentication to be enforced commensurate with risk."),
            _control("nist_csf", "NIST.PR.AA.04", "NIST also expects identity assertions to be protected, conveyed, and verified."),
            _control("pci_dss", "PCI.8.1", "PCI DSS requires defined identification and authentication processes."),
            _control("pci_dss", "PCI.8.2", "PCI DSS requires user identification and authentication to be managed."),
            _control("pci_dss", "PCI.8.3", "PCI DSS expects strong authentication factors for access to the CDE."),
            _control("pci_dss", "PCI.8.4", "PCI DSS requires MFA for access to the cardholder data environment."),
            _control("pci_dss", "PCI.8.5", "PCI DSS expects MFA systems to be configured securely."),
            _control("pci_dss", "PCI.8.6", "PCI DSS expects system and application accounts to be managed."),
        ],
        tags=['security', 'authentication', 'credential-management', 'encryption'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_009",
        "Privileged And Administrative Access Safeguards",
        "Are privileged, administrative, and source-code-related access pathways tightly restricted, monitored, and justified?",
        "Look for privileged access criteria, break-glass control, approval and logging, source code restrictions, and controls over utility or administrative tooling.",
        [
            _control("iso27001", "ISO.A8.2"),
            _control("iso27001", "ISO.A8.18"),
            _control("iso27001", "ISO.A8.4"),
            _control("hipaa", "HIPAA.164.312a2", "HIPAA requires an emergency access procedure for obtaining ePHI during an emergency."),
        ],
        tags=['security', 'access-control', 'privileged-access', 'source-code'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_010",
        "Processor And Supplier Due Diligence",
        "Does the organization assess privacy and security risk before engaging processors, vendors, or suppliers that will handle personal data or support critical systems?",
        "Look for onboarding due diligence, security questionnaires, risk tiering, approval criteria, and decision records for processors and suppliers.",
        [
            _control("dpdpa", "CH2.SECURITY.3", "DPDPA expects contractual safeguards with data processors."),
            _control("iso27001", "ISO.A5.19", "ISO requires processes to manage supplier-related information security risks."),
            _control("gdpr", "GDPR.ART28.1", "GDPR requires use of processors that provide sufficient guarantees."),
            _control("nist_csf", "NIST.GV.SC.01", "NIST expects a supply chain risk management program to be established."),
            _control("nist_csf", "NIST.GV.SC.04", "NIST also expects suppliers to be assessed prior to engagement."),
            _control("pci_dss", "PCI.12.8", "PCI DSS requires risk from third-party relationships to be managed."),
        ],
        tags=['third-party', 'processor-management', 'supplier-management', 'risk-assessment'],
        criticality="critical",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_011",
        "Processor Contracts And Data Processing Terms",
        "Are supplier and processor contracts documented with the privacy and security terms needed to govern personal data processing?",
        "Look for DPAs or equivalent clauses covering instructions, confidentiality, safeguards, breach duties, audit rights, deletion or return, and subcontracting restrictions.",
        [
            _control("iso27001", "ISO.A5.20"),
            _control("gdpr", "GDPR.ART28.2", "GDPR expects formal processor contract terms under Art 28."),
            _control("hipaa", "HIPAA.164.308b1", "HIPAA's business associate agreement requirement maps to formal processor contract terms."),
            _control("nist_csf", "NIST.GV.SC.05", "NIST expects supply chain requirements to be incorporated into contracts."),
            _control("pci_dss", "PCI.12.9", "PCI DSS requires service providers to support the customer's PCI DSS compliance via contractual acknowledgement."),
        ],
        tags=['third-party', 'contracts', 'data-processing-agreement', 'supplier-management'],
        criticality="critical",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_012",
        "Supply Chain And Sub-Processor Oversight",
        "Does the organization govern extended supply-chain risk, including sub-processors and outsourced development arrangements?",
        "Look for approval of sub-processors, flow-down obligations, supplier chain visibility, and governance over outsourced engineering or service delivery.",
        [
            _control("iso27001", "ISO.A5.21"),
            _control("iso27001", "ISO.A8.30"),
            _control("gdpr", "GDPR.ART28.3", "GDPR expects sub-processor authorization and oversight."),
            _control("nist_csf", "NIST.GV.SC.03", "NIST expects supply chain risk management to be integrated into broader risk processes."),
        ],
        tags=['third-party', 'supply-chain', 'sub-processor', 'outsourced-development'],
        criticality="high",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_013",
        "Ongoing Supplier Monitoring",
        "Are suppliers, cloud services, and externally managed network services monitored and reviewed throughout the relationship?",
        "Look for periodic review cadence, change notifications, performance and control monitoring, cloud governance, and reassessment of third-party security posture.",
        [
            _control("iso27001", "ISO.A5.22"),
            _control("iso27001", "ISO.A5.23"),
            _control("iso27001", "ISO.A8.21"),
            _control("nist_csf", "NIST.GV.SC.02", "NIST expects supplier cybersecurity requirements to be established and monitored over the relationship."),
        ],
        tags=['third-party', 'monitoring', 'cloud-security', 'service-management'],
        criticality="high",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_014",
        "Incident Response Planning And Workforce Reporting",
        "Does the organization maintain an incident response plan and require personnel to escalate security events through a defined reporting path?",
        "Look for an approved response plan, roles, reporting channels, training or awareness, and evidence that employees know how to report incidents.",
        [
            _control("dpdpa", "BN.NOTIFY.3", "DPDPA expects a documented incident response plan."),
            _control("iso27001", "ISO.A5.24", "ISO expects planning and preparation for incident management."),
            _control("iso27001", "ISO.A6.8", "ISO expects personnel to report information security events."),
            _control("hipaa", "HIPAA.164.308a7iv", "HIPAA expects testing and revision procedures for contingency plans."),
            _control("nist_csf", "NIST.RS.MA.01", "NIST expects the incident response plan to be executed once an incident is declared."),
            _control("nist_csf", "NIST.PR.IR.02", "NIST expects cybersecurity incident handling capability to be in place."),
            _control("pci_dss", "PCI.12.10", "PCI DSS requires security incidents to be responded to immediately."),
        ],
        tags=['incident-response', 'incident-response-plan', 'reporting'],
        criticality="critical",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_015",
        "Incident Assessment And Containment",
        "Does the organization triage security events promptly and execute documented response actions to contain and manage confirmed incidents?",
        "Look for severity criteria, decision logs, containment playbooks, responder roles, and records showing that incidents move from detection to action without delay.",
        [
            _control("iso27001", "ISO.A5.25"),
            _control("iso27001", "ISO.A5.26"),
            _control("nist_csf", "NIST.RS.MA.02", "NIST expects incidents to be triaged and prioritized consistently with the response plan."),
            _control("nist_csf", "NIST.RS.MA.03", "NIST also expects incidents to be categorized."),
            _control("nist_csf", "NIST.RS.MA.04", "NIST expects incidents to be escalated as needed."),
            _control("nist_csf", "NIST.RS.MA.05", "NIST expects criteria for incident management actions to be applied."),
            _control("nist_csf", "NIST.RS.MI.01", "NIST expects incidents to be contained."),
            _control("nist_csf", "NIST.RS.MI.02", "NIST also expects incidents to be eradicated."),
            _control("nist_csf", "NIST.DE.AE.06", "NIST expects clear criteria for declaring an incident from detected events."),
        ],
        tags=['incident-response', 'triage', 'breach-management', 'containment'],
        criticality="high",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_016",
        "Incident Evidence, Documentation, And Lessons Learned",
        "Does the organization preserve incident evidence, maintain a breach register, and feed lessons learned back into control improvements?",
        "Look for incident logs, evidence preservation guidance, post-incident reviews, corrective actions, and a maintained breach or incident register.",
        [
            _control("dpdpa", "BN.NOTIFY.4", "DPDPA expects a breach register to be maintained."),
            _control("iso27001", "ISO.A5.27", "ISO expects lessons learned from incidents."),
            _control("iso27001", "ISO.A5.28", "ISO expects collection of evidence."),
            _control("gdpr", "GDPR.ART33.2", "GDPR requires breach documentation sufficient to demonstrate compliance."),
            _control("nist_csf", "NIST.RS.AN.03", "NIST expects root cause analysis to be performed."),
            _control("nist_csf", "NIST.RS.AN.06", "NIST also expects investigation actions to be taken and documented."),
            _control("nist_csf", "NIST.RS.AN.07", "NIST expects incident data to be collected and analyzed."),
            _control("nist_csf", "NIST.RS.AN.08", "NIST expects incident magnitude and scope to be estimated."),
            _control("nist_csf", "NIST.ID.IM.01", "NIST expects improvements to be identified from lessons learned during incidents."),
            _control("nist_csf", "NIST.ID.IM.02", "NIST also expects improvements identified from security tests and exercises."),
            _control("nist_csf", "NIST.ID.IM.03", "NIST expects improvements identified from third-party threat and incident information."),
        ],
        tags=['incident-response', 'breach-register', 'documentation', 'lessons-learned'],
        criticality="high",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_017",
        "Regulatory And Supervisory Breach Notification",
        "Can the organization determine when a breach must be reported to a regulator or supervisory authority and do so within the required timeframe?",
        "Look for notification criteria, authority contact points, decision ownership, timelines, escalation workflow, and retained evidence of notifications made or decisions not to notify.",
        [
            _control("dpdpa", "BN.NOTIFY.1", "DPDPA requires notification to the Data Protection Board and affected parties as prescribed."),
            _control("iso27001", "ISO.A5.5", "ISO expects maintained contact with relevant authorities."),
            _control("gdpr", "GDPR.ART33.1", "GDPR requires supervisory authority notification without undue delay where risk thresholds are met."),
            _control("gdpr", "GDPR.ART31.1", "GDPR also expects cooperation with the supervisory authority."),
            _control("hipaa", "HIPAA.164.406", "HIPAA requires notification to HHS following a breach."),
            _control("hipaa", "HIPAA.164.408", "HIPAA also requires notification to the media for breaches affecting more than 500 individuals in a state or jurisdiction."),
            _control("nist_csf", "NIST.RS.CO.02", "NIST expects internal stakeholders to be notified of incidents."),
            _control("nist_csf", "NIST.RS.CO.03", "NIST also expects incident information to be shared with designated external parties."),
            _control("nist_csf", "NIST.RS.CO.04", "NIST expects voluntary incident information sharing with external stakeholders."),
            _control("gdpr", "GDPR.ART33.3", "GDPR requires processors to notify controllers without undue delay after becoming aware of a breach."),
        ],
        tags=['incident_response', 'breach-notification', 'regulatory-notification'],
        criticality="critical",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_018",
        "Breach Communication To Affected Individuals",
        "Does the organization have a process to notify affected individuals when a personal data breach creates material risk to them?",
        "Look for risk assessment, message templates, approval path, delivery channels, and records of when individual notification is triggered or suppressed with justification.",
        [
            _control("dpdpa", "BN.NOTIFY.2", "DPDPA expects notice to affected Data Principals where applicable."),
            _control("gdpr", "GDPR.ART34.1", "GDPR requires communication to data subjects when the breach is likely to result in high risk."),
            _control("hipaa", "HIPAA.164.404a", "HIPAA requires notification to affected individuals following discovery of a breach."),
            _control("hipaa", "HIPAA.164.414", "HIPAA also imposes breach notification obligations on business associates."),
        ],
        tags=['incident-response', 'breach-notification', 'data-subject-notification'],
        criticality="critical",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_019",
        "Incident Resilience And ICT Continuity",
        "Are systems and processes designed to remain resilient and recoverable during security incidents or service disruptions?",
        "Look for resilience objectives, continuity plans, failover or recovery testing, and evidence that critical services can continue or recover in a controlled manner.",
        [
            _control("iso27001", "ISO.A5.30"),
            _control("gdpr", "GDPR.ART32.3", "GDPR expects resilience and availability measures appropriate to risk."),
            _control("hipaa", "HIPAA.164.308a7i", "HIPAA's data backup plan requirement underpins resilience and recovery."),
            _control("hipaa", "HIPAA.164.308a7ii", "HIPAA's disaster recovery plan requirement maps directly to ICT continuity."),
            _control("hipaa", "HIPAA.164.308a7iii", "HIPAA's emergency mode operation plan keeps critical functions running during disruption."),
            _control("nist_csf", "NIST.RC.RP.01", "NIST expects the recovery plan to be executed during or after an incident."),
            _control("nist_csf", "NIST.RC.RP.02", "NIST also expects recovery actions to be selected based on criteria."),
            _control("nist_csf", "NIST.RC.RP.03", "NIST expects recovery activities to be verified."),
            _control("nist_csf", "NIST.RC.RP.04", "NIST expects critical mission functions to be considered during recovery."),
            _control("nist_csf", "NIST.RC.RP.05", "NIST expects completeness of recovery to be verified."),
            _control("nist_csf", "NIST.RC.RP.06", "NIST expects the end of recovery to be formally declared."),
            _control("nist_csf", "NIST.PR.DS.11", "NIST expects data backups to be created, protected, and tested."),
            _control("nist_csf", "NIST.PR.IR.04", "NIST expects adequate resource capacity to maintain resilience during disruption."),
            _control("iso27001", "ISO.A5.29", "ISO expects information security to be maintained during disruption."),
            _control("iso27001", "ISO.A8.6", "ISO expects capacity management to prevent resource exhaustion during disruptions."),
            _control("iso27001", "ISO.A8.13", "ISO expects information backup as part of resilience."),
            _control("iso27001", "ISO.A8.14", "ISO expects redundancy of information processing facilities for availability."),
        ],
        tags=['incident-response', 'business-continuity', 'resilience', 'availability'],
        criticality="high",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_020",
        "Transparent Privacy Notice At Collection",
        "Does the organization provide a clear and accessible privacy notice at or before collection that explains the processing in plain language?",
        "Look for layered notice design, intelligible language, publication points, and disclosure of identity, purposes, recipients, rights, retention, and key privacy contacts.",
        [
            _control("dpdpa", "CH2.NOTICE.1", "DPDPA requires notice at or before collection."),
            _control("iso27001", "ISO.A5.34", "ISO expects privacy and protection of personal information controls around PII processing."),
            _control("gdpr", "GDPR.ART12.1", "GDPR requires concise, transparent, intelligible communication."),
            _control("gdpr", "GDPR.ART12.2", "GDPR encourages layered and accessible notices."),
            _control("gdpr", "GDPR.ART13.1", "GDPR specifies the content required when data is collected directly."),
            _control("hipaa", "HIPAA.164.520", "HIPAA requires a notice of privacy practices describing how PHI is used and disclosed."),
        ],
        tags=['data-protection', 'privacy-notice', 'transparency', 'communication'],
        criticality="critical",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_021",
        "Notice For Legacy And Indirect Collection",
        "Can the organization provide privacy notice when data was collected previously or obtained indirectly from another source?",
        "Look for retrospective notification workflows, indirect-collection notice triggers, timing rules, and evidence that notice reaches affected individuals when required.",
        [
            _control("dpdpa", "CH2.NOTICE.2", "DPDPA expects notice for personal data collected before the Act where applicable."),
            _control("gdpr", "GDPR.ART14.1", "GDPR requires notice when data is obtained indirectly."),
        ],
        tags=['data-protection', 'privacy-notice', 'legacy-data', 'third-party-data'],
        criticality="high",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_022",
        "Privacy Contact Point And Complaint Intake",
        "Does the organization publish a usable privacy contact point and intake channel for complaints or data rights requests?",
        "Look for named contact details, channel visibility, routing, triage ownership, and evidence that privacy grievances are received and logged rather than lost in general support.",
        [
            _control("dpdpa", "CH2.NOTICE.3", "DPDPA notice content should include DPO or grievance officer contact details."),
            _control("dpdpa", "CH3.GRIEVANCE.1", "DPDPA expects a grievance redressal mechanism to be available."),
            _control("dpdpa", "CH3.GRIEVANCE.2", "DPDPA expects timely grievance response and informing Data Principals of their right to approach the Data Protection Board."),
        ],
        tags=['data-protection', 'privacy-notice', 'dpo', 'grievance-redressal'],
        criticality="high",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_023",
        "Access Request Fulfillment",
        "Can individuals request access to their personal data and receive the response through a defined, timely fulfillment process?",
        "Look for intake, identity verification, retrieval workflow, response template, SLA tracking, and evidence that the organization can actually produce the requested information.",
        [
            _control("dpdpa", "CH3.ACCESS.1", "DPDPA grants access to a summary of personal data and processing activities."),
            _control("gdpr", "GDPR.ART15.1", "GDPR defines the right of access and required response content."),
            _control("gdpr", "GDPR.ART15.2", "GDPR also expects a documented request-handling process."),
            _control("hipaa", "HIPAA.164.524", "HIPAA grants individuals the right of access to their own PHI."),
        ],
        tags=['consent_rights', 'data-subject-rights', 'right-of-access', 'process'],
        criticality="critical",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_024",
        "Rectification And Data Quality",
        "Does the organization maintain processes to keep personal data accurate and to correct it when an individual or business owner identifies an error?",
        "Look for correction workflow, ownership for data quality, validation steps, downstream updates, and records showing corrections are carried through affected systems.",
        [
            _control("dpdpa", "CH2.ACCURACY.1", "DPDPA requires reasonable efforts to ensure accuracy."),
            _control("dpdpa", "CH3.CORRECT.1", "DPDPA provides a correction and completion mechanism."),
            _control("gdpr", "GDPR.ART16.1", "GDPR grants the right to rectification."),
            _control("gdpr", "GDPR.ART5D.1", "GDPR also treats accuracy as a core processing principle."),
            _control("hipaa", "HIPAA.164.526", "HIPAA grants individuals the right to request amendment of their PHI."),
        ],
        tags=['consent_rights', 'data-quality', 'rectification', 'accuracy'],
        criticality="high",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_025",
        "Erasure, Retention, And Deletion Execution",
        "Does the organization enforce retention limits and execute deletion or erasure requests through documented workflows and technical controls?",
        "Look for retention schedules, deletion triggers, technical execution steps, exception handling, system coverage, and evidence that data is deleted when no longer needed or when rights are exercised.",
        [
            _control("dpdpa", "CH2.MINIMIZE.2", "DPDPA limits retention to the period necessary for the purpose."),
            _control("dpdpa", "CH2.MINIMIZE.3", "DPDPA expects retention schedules and deletion procedures."),
            _control("dpdpa", "CH3.CORRECT.2", "DPDPA includes a mechanism for erasure."),
            _control("iso27001", "ISO.A8.10", "ISO expects controlled information deletion."),
            _control("gdpr", "GDPR.ART17.1", "GDPR grants the right to erasure."),
            _control("gdpr", "GDPR.ART5E.1", "GDPR treats storage limitation as a core principle."),
        ],
        tags=['data-protection', 'data-retention', 'data-deletion', 'right-to-erasure'],
        criticality="critical",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_026",
        "Downstream Recipient Notification After Data Changes",
        "When data is corrected, erased, or restricted, does the organization notify recipients or downstream parties that received the data where required?",
        "Look for recipient inventories, downstream communication workflows, exception logging, and evidence that third parties are informed after data changes.",
        [
            _control("gdpr", "GDPR.ART17.2"),
            _control("gdpr", "GDPR.ART19.1"),
        ],
        tags=['consent_rights', 'notification', 'third-party', 'right-to-erasure'],
        criticality="medium",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_027",
        "Restriction, Objection, And Automated Decision Safeguards",
        "Can the organization restrict processing, honor objections, and provide safeguards when automated decision-making materially affects individuals?",
        "Look for objection channels, restriction flags, suppression of challenged processing, human review capability, and records of how profiling or automated decisions are explained and contested.",
        [
            _control("gdpr", "GDPR.ART18.1"),
            _control("gdpr", "GDPR.ART21.1"),
            _control("gdpr", "GDPR.ART22.1"),
            _control("gdpr", "GDPR.ART22.2"),
        ],
        tags=['consent_rights', 'data-subject-rights', 'restriction', 'automated-decision-making'],
        criticality="high",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_028",
        "Portability And Authorized Representative Requests",
        "Can the organization respond when an individual or authorized representative seeks a portable copy of personal data or acts on the individual's behalf?",
        "Look for representation validation, export workflow, machine-readable output capability, and evidence that the organization can differentiate portability from ordinary access responses.",
        [
            _control("dpdpa", "CH3.NOMINATE.1", "DPDPA includes a nomination mechanism for death or incapacity."),
            _control("gdpr", "GDPR.ART20.1", "GDPR grants the right to portability for qualifying processing."),
        ],
        tags=['consent_rights', 'data-subject-rights', 'nomination', 'data-portability'],
        criticality="medium",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_029",
        "Consent Governance, Records, And Granularity",
        "Where consent is relied on, does the organization obtain it in a specific and granular way, keep records, and refresh or re-seek it when needed?",
        "Look for lawful-basis documentation, consent evidence, granular choice capture, refresh triggers, and controls preventing bundled or stale consent from being reused indefinitely.",
        [
            _control("dpdpa", "CH2.CONSENT.1", "DPDPA requires free, specific, informed consent as the lawful basis."),
            _control("dpdpa", "CM.RECORDS.1", "DPDPA add-on controls expect auditable consent records."),
            _control("dpdpa", "CM.RECORDS.2", "DPDPA add-on controls expect consent refresh on purpose change or staleness."),
            _control("dpdpa", "CM.GRANULAR.1", "DPDPA add-on controls expect granular consent by processing purpose."),
            _control("dpdpa", "CM.GRANULAR.2", "DPDPA add-on controls guard against bundled or manipulative consent design."),
            _control("gdpr", "GDPR.ART6.1", "GDPR requires identification and documentation of the lawful basis."),
            _control("gdpr", "GDPR.ART6.2", "GDPR requires consent to be freely given, specific, informed, and easy to withdraw."),
            _control("hipaa", "HIPAA.164.508a", "HIPAA requires authorization for uses and disclosures of PHI not otherwise permitted."),
            _control("dpdpa", "CH2.CONSENT.2", "DPDPA expects separate itemised consent for each processing purpose."),
        ],
        tags=['consent_rights', 'consent', 'consent-records', 'granular-consent'],
        criticality="critical",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_030",
        "Consent Withdrawal And Interoperable Choice Management",
        "Can individuals withdraw consent easily and, where used, is consent management implemented in an interoperable way across channels or processing contexts?",
        "Look for user-facing withdrawal controls, propagation of withdrawal, suppression of further processing, and evidence that consent preferences are synchronized rather than left fragmented.",
        [
            _control("dpdpa", "CH2.CONSENT.3"),
            _control("dpdpa", "CH2.CONSENT.4"),
        ],
        tags=['consent_rights', 'consent', 'consent-withdrawal', 'consent-management'],
        criticality="high",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_031",
        "Cross-Border Transfer Governance",
        "Does the organization know when personal data leaves the originating jurisdiction and apply documented transfer governance, safeguards, and localization controls where required?",
        "Look for transfer inventories, destination mapping, contractual or legal safeguards, approved transfer routes, and restrictions on prohibited or unmanaged transfer patterns.",
        [
            _control("dpdpa", "CB.TRANSFER.1", "DPDPA expects awareness of cross-border transfer routes and destinations."),
            _control("dpdpa", "CB.TRANSFER.2", "DPDPA expects documented transfer safeguards."),
            _control("dpdpa", "CB.TRANSFER.3", "DPDPA may require localization or residency constraints for certain processing contexts."),
            _control("iso27001", "ISO.A5.14", "ISO requires governed information transfer rules and agreements."),
            _control("gdpr", "GDPR.ART44.1", "GDPR sets transfer principles and governance for international transfers."),
            _control("gdpr", "GDPR.ART45.1", "GDPR permits transfers to countries with an adequacy decision."),
            _control("gdpr", "GDPR.ART46.1", "GDPR permits transfers under appropriate safeguards such as Standard Contractual Clauses."),
            _control("gdpr", "GDPR.ART47.1", "GDPR permits intra-group transfers under Binding Corporate Rules."),
            _control("gdpr", "GDPR.ART49.1", "GDPR permits derogations for specific situations when no other transfer mechanism applies."),
        ],
        tags=['cross_border', 'data-transfer', 'data-localization', 'governance'],
        criticality="high",
        domain_group="cross_border",
    ),
    _cluster(
        "CLUSTER_032",
        "Children'S Data And Age Verification",
        "If the organization processes children's data, does it prevent harmful processing and verify age or parental authorization as required?",
        "Look for age-threshold rules, parental authorization controls, child-specific restrictions, and evidence that elevated protections are enforced in practice rather than stated only in policy.",
        [
            _control("dpdpa", "CH4.CHILD.1"),
            _control("dpdpa", "CH4.CHILD.2"),
            _control("dpdpa", "CH4.CHILD.3"),
            _control("dpdpa", "CH2.CONSENT.5", "DPDPA requires verifiable consent of a parent or lawful guardian before processing a child's personal data."),
        ],
        tags=['children_vulnerable', 'children-data', 'age-verification', 'harm-prevention'],
        criticality="high",
        domain_group="children_vulnerable",
    ),
    _cluster(
        "CLUSTER_033",
        "Acceptable Use, Employment Obligations, And Confidentiality",
        "Are personnel and contracted users bound by documented acceptable-use, employment, and confidentiality obligations relevant to protecting information?",
        "Look for acceptable-use rules, security responsibilities in employment terms, NDAs, acknowledgement records, and evidence that obligations are communicated before access is granted.",
        [
            _control("iso27001", "ISO.A5.10"),
            _control("iso27001", "ISO.A6.2"),
            _control("iso27001", "ISO.A6.6"),
            _control("nist_csf", "NIST.GV.RR.04", "NIST expects cybersecurity to be considered in human resources practices."),
            _control("pci_dss", "PCI.12.2", "PCI DSS requires acceptable use policies for end-user technologies."),
            _control("pci_dss", "PCI.12.7", "PCI DSS requires personnel to be screened to reduce insider threat risk."),
            _control("iso27001", "ISO.A6.1", "ISO expects background screening of personnel before employment."),
            _control("iso27001", "ISO.A6.4", "ISO expects a disciplinary process for security policy violations."),
        ],
        tags=['governance', 'policy', 'responsibilities', 'confidentiality'],
        criticality="medium",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_034",
        "Classification, Labelling, Media Handling, And Secure Disposal",
        "Does the organization classify and label information appropriately and handle storage media and equipment disposal in a way that prevents unauthorized disclosure?",
        "Look for classification scheme, labelling standards, media handling procedures, secure disposal evidence, and alignment between classification and operational handling rules.",
        [
            _control("iso27001", "ISO.A5.12"),
            _control("iso27001", "ISO.A5.13"),
            _control("iso27001", "ISO.A7.10"),
            _control("iso27001", "ISO.A7.14"),
            _control("nist_csf", "NIST.ID.AM.07", "NIST expects data to be classified consistent with risk strategy."),
            _control("hipaa", "HIPAA.164.310d1", "HIPAA requires policies for the disposal of media containing ePHI."),
            _control("hipaa", "HIPAA.164.310d2", "HIPAA also requires media re-use procedures to remove ePHI before reuse."),
            _control("pci_dss", "PCI.9.4", "PCI DSS requires media containing cardholder data to be physically protected and securely disposed of."),
        ],
        tags=['data-protection', 'classification', 'media-handling', 'secure-disposal'],
        criticality="medium",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_035",
        "Risk Register And Threat Intelligence",
        "Does the organization maintain a formal risk register, identify threats and vulnerabilities on an ongoing basis, and select risk treatments based on documented criteria?",
        "Look for a maintained risk register, threat intelligence sources, vulnerability identification, risk prioritization criteria, and evidence that response options are formally selected rather than ad hoc.",
        [
            _control("nist_csf", "NIST.ID.RA.01", "NIST expects vulnerabilities to be identified and recorded."),
            _control("nist_csf", "NIST.ID.RA.02", "NIST expects cyber threat intelligence to be received and analyzed."),
            _control("nist_csf", "NIST.ID.RA.03", "NIST expects internal and external threats to be identified and recorded."),
            _control("nist_csf", "NIST.ID.RA.04", "NIST expects potential impacts and likelihoods to be used to prioritize risk."),
            _control("nist_csf", "NIST.ID.RA.05", "NIST expects threats, vulnerabilities, and impacts to be used to determine risk."),
            _control("nist_csf", "NIST.ID.RA.06", "NIST expects risk responses to be chosen, prioritized, and tracked."),
            _control("nist_csf", "NIST.GV.RM.03", "NIST expects risk management activities to be performed continuously."),
            _control("nist_csf", "NIST.GV.RM.04", "NIST expects strategic direction on risk to be established and communicated."),
            _control("hipaa", "HIPAA.164.308a1i", "HIPAA's risk analysis requirement underpins the risk register."),
            _control("hipaa", "HIPAA.164.308a1ii", "HIPAA's risk management requirement drives treatment selection."),
            _control("pci_dss", "PCI.12.3", "PCI DSS requires risks to the CDE to be formally identified, evaluated, and managed."),
            _control("iso27001", "ISO.A5.6", "ISO expects contact with special interest groups to inform threat awareness."),
            _control("iso27001", "ISO.A5.7", "ISO expects threat intelligence to be collected and evaluated."),
        ],
        tags=['governance', 'risk-management', 'threat-intelligence', 'risk-register'],
        criticality="high",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_036",
        "Security Awareness And Training",
        "Does the organization run an ongoing security awareness program and provide role-based training for personnel who access systems or handle protected data?",
        "Look for a training curriculum, completion tracking, role-specific content, refresher cadence, and evidence that training extends beyond a one-time onboarding event.",
        [
            _control("hipaa", "HIPAA.164.308a5i", "HIPAA requires a security awareness and training program for all workforce members."),
            _control("hipaa", "HIPAA.164.308a5ii", "HIPAA expects periodic security reminders to reinforce training."),
            _control("nist_csf", "NIST.PR.AT.01", "NIST requires a security awareness program for personnel."),
            _control("nist_csf", "NIST.PR.AT.02", "NIST also expects role-based security training for personnel with specialized responsibilities."),
            _control("pci_dss", "PCI.12.6", "PCI DSS requires ongoing security awareness education for personnel."),
            _control("iso27001", "ISO.A6.3", "ISO expects an information security awareness, education, and training program."),
        ],
        tags=['governance', 'training', 'security-awareness', 'personnel'],
        criticality="medium",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_038",
        "Secure Configuration And Hardening",
        "Are systems, software, and network components configured to documented secure baselines, with vendor defaults changed and unnecessary functionality removed?",
        "Look for hardening standards, baseline configuration documents, vendor default account remediation, wireless configuration controls, and evidence baselines are kept current as systems change.",
        [
            _control("nist_csf", "NIST.PR.PS.01", "NIST expects hardware configurations to be managed."),
            _control("nist_csf", "NIST.PR.PS.02", "NIST expects software configurations to be managed."),
            _control("nist_csf", "NIST.PR.PS.03", "NIST expects software installation to be controlled."),
            _control("nist_csf", "NIST.PR.PS.05", "NIST expects the technology lifecycle to be managed."),
            _control("pci_dss", "PCI.2.1", "PCI DSS requires defined and understood secure configuration processes."),
            _control("pci_dss", "PCI.2.2", "PCI DSS requires system components to be configured and managed securely."),
            _control("pci_dss", "PCI.2.3", "PCI DSS requires wireless environments to be configured and managed securely."),
            _control("pci_dss", "PCI.2.4", "PCI DSS requires vendor default accounts to be managed."),
            _control("pci_dss", "PCI.2.5", "PCI DSS expects primary functions to be separated onto different servers."),
            _control("iso27001", "ISO.A8.1", "ISO expects user endpoint devices to be configured and managed securely."),
            _control("iso27001", "ISO.A8.9", "ISO expects configuration management of hardware and software."),
            _control("iso27001", "ISO.A8.19", "ISO expects installation of software on operational systems to be controlled."),
            _control("nist_csf", "NIST.ID.AM.08", "NIST expects systems, hardware, and software to be managed throughout their lifecycle including decommissioning."),
        ],
        tags=['security', 'configuration-management', 'hardening', 'secure-baseline'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_039",
        "Malware And Endpoint Protection",
        "Are anti-malware and anti-phishing controls deployed and maintained across endpoints and systems that process protected data?",
        "Look for anti-malware deployment coverage, signature or behavior update cadence, anti-phishing mechanisms, and evidence that protections remain active and aren't disabled by end users.",
        [
            _control("hipaa", "HIPAA.164.308a5iii", "HIPAA requires procedures to guard against and detect malicious software."),
            _control("pci_dss", "PCI.5.1", "PCI DSS requires defined and understood malware protection processes."),
            _control("pci_dss", "PCI.5.2", "PCI DSS requires malicious software to be prevented or detected and addressed."),
            _control("pci_dss", "PCI.5.3", "PCI DSS requires anti-malware mechanisms to be active and maintained."),
            _control("pci_dss", "PCI.5.4", "PCI DSS requires anti-phishing mechanisms to be in place."),
            _control("iso27001", "ISO.A8.7", "ISO expects protection against malware to be implemented and maintained."),
            _control("iso27001", "ISO.A8.23", "ISO expects web filtering to protect against malicious content."),
        ],
        tags=['security', 'malware-protection', 'endpoint-security', 'anti-phishing'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_040",
        "Network Segmentation And Perimeter Controls",
        "Are network security controls and segmentation in place to restrict access paths into environments that process sensitive or regulated data?",
        "Look for network diagrams, segmentation boundaries, firewall/NSC rule reviews, restrictions on connections to untrusted networks, and evidence that the perimeter is actively maintained.",
        [
            _control("nist_csf", "NIST.PR.IR.01", "NIST expects networks and environments to be protected from unauthorized access."),
            _control("nist_csf", "NIST.PR.IR.03", "NIST expects network topology to be documented and managed."),
            _control("pci_dss", "PCI.1.1", "PCI DSS requires network security controls to be defined and understood."),
            _control("pci_dss", "PCI.1.2", "PCI DSS requires network security controls to be configured and maintained."),
            _control("pci_dss", "PCI.1.3", "PCI DSS requires network access to and from the CDE to be restricted."),
            _control("pci_dss", "PCI.1.4", "PCI DSS requires network connections between trusted and untrusted networks to be controlled."),
            _control("pci_dss", "PCI.1.5", "PCI DSS requires risks from computing devices on both trusted and untrusted networks to be managed."),
            _control("iso27001", "ISO.A8.20", "ISO expects network security controls to be implemented and maintained."),
            _control("iso27001", "ISO.A8.22", "ISO expects segregation of networks to isolate security domains."),
        ],
        tags=['security', 'network-segmentation', 'perimeter-security', 'network-controls'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_041",
        "Cryptography And Data Protection At Rest And In Transit",
        "Is sensitive data protected with appropriate cryptographic controls wherever it is stored or transmitted, and are integrity controls applied to detect unauthorized alteration?",
        "Look for encryption standards, key management practices, transmission protection, integrity verification mechanisms, and evidence that protections are applied consistently across storage and transit.",
        [
            _control("hipaa", "HIPAA.164.312a4", "HIPAA requires a mechanism to encrypt and decrypt ePHI."),
            _control("hipaa", "HIPAA.164.312e1", "HIPAA requires integrity controls to protect ePHI in transmission."),
            _control("hipaa", "HIPAA.164.312e2", "HIPAA expects encryption of ePHI during transmission where reasonable and appropriate."),
            _control("hipaa", "HIPAA.164.312e3", "HIPAA expects secure handling of ePHI sent via messaging and email."),
            _control("hipaa", "HIPAA.164.312e4", "HIPAA expects remote access to ePHI to be secured."),
            _control("hipaa", "HIPAA.164.312c1", "HIPAA requires integrity controls to protect ePHI from improper alteration or destruction."),
            _control("hipaa", "HIPAA.164.312c2", "HIPAA expects authentication mechanisms to corroborate that ePHI has not been altered."),
            _control("nist_csf", "NIST.PR.DS.01", "NIST expects data at rest to be protected."),
            _control("nist_csf", "NIST.PR.DS.02", "NIST expects data in transit to be protected."),
            _control("nist_csf", "NIST.PR.DS.10", "NIST expects data in use to be protected."),
            _control("pci_dss", "PCI.3.5", "PCI DSS requires the PAN to be secured wherever it is stored."),
            _control("pci_dss", "PCI.3.6", "PCI DSS requires cryptographic keys protecting stored account data to be secured."),
            _control("pci_dss", "PCI.4.1", "PCI DSS requires defined and understood transmission protection processes."),
            _control("pci_dss", "PCI.4.2", "PCI DSS requires the PAN to be protected with strong cryptography during transmission."),
            _control("pci_dss", "PCI.4.3", "PCI DSS requires trusted keys and certificates to be managed."),
            _control("pci_dss", "PCI.4.4", "PCI DSS requires the PAN to be protected when sent via end-user messaging technologies."),
            _control("iso27001", "ISO.A8.11", "ISO expects data masking to reduce exposure of sensitive information."),
            _control("iso27001", "ISO.A8.12", "ISO expects data leakage prevention controls to protect against exfiltration."),
            _control("iso27001", "ISO.A8.24", "ISO expects appropriate use of cryptography including key management."),
        ],
        tags=['security', 'encryption', 'cryptography', 'data-integrity'],
        criticality="critical",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_042",
        "Logging, Monitoring, And Audit Trail Integrity",
        "Are audit logs generated, protected from tampering, and reviewed regularly across systems that process sensitive or regulated data?",
        "Look for log generation coverage, retention periods, tamper-protection, review cadence, time synchronization, and evidence that anomalies surfaced in logs are followed up.",
        [
            _control("hipaa", "HIPAA.164.308a1iv", "HIPAA requires regular review of information system activity records."),
            _control("hipaa", "HIPAA.164.308a5iv", "HIPAA expects log-in monitoring procedures."),
            _control("hipaa", "HIPAA.164.312b", "HIPAA requires audit controls to record and examine activity in systems with ePHI."),
            _control("hipaa", "HIPAA.164.312b2", "HIPAA expects audit logs to actually be reviewed, not just recorded."),
            _control("nist_csf", "NIST.PR.PS.04", "NIST expects log records to be generated and made available for monitoring."),
            _control("nist_csf", "NIST.DE.CM.03", "NIST expects personnel activity to be monitored for potentially adverse events."),
            _control("nist_csf", "NIST.DE.CM.09", "NIST expects computing hardware and software to be monitored for potentially adverse events."),
            _control("pci_dss", "PCI.10.1", "PCI DSS requires defined and understood logging processes."),
            _control("pci_dss", "PCI.10.2", "PCI DSS requires audit logs to be enabled and capturing required events."),
            _control("pci_dss", "PCI.10.3", "PCI DSS requires audit logs to be protected from destruction and unauthorized modification."),
            _control("pci_dss", "PCI.10.4", "PCI DSS requires audit logs to be reviewed to identify anomalies."),
            _control("pci_dss", "PCI.10.5", "PCI DSS requires time-synchronization mechanisms for consistent audit logs."),
            _control("iso27001", "ISO.A8.15", "ISO expects logging to be implemented and logs protected."),
            _control("iso27001", "ISO.A8.16", "ISO expects monitoring of systems to detect anomalies and unauthorized activities."),
            _control("iso27001", "ISO.A8.17", "ISO expects clock synchronization across systems for consistent log correlation."),
            _control("iso27001", "ISO.A5.33", "ISO expects records to be protected from loss, destruction, falsification, and unauthorized access."),
        ],
        tags=['security', 'logging', 'monitoring', 'audit-trail'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_043",
        "Vulnerability Management And Penetration Testing",
        "Does the organization identify, prioritize, and remediate vulnerabilities in systems and applications, including through recurring penetration testing?",
        "Look for vulnerability scanning cadence, remediation SLAs by severity, penetration testing scope and frequency, and evidence that findings are tracked through to closure.",
        [
            _control("pci_dss", "PCI.11.1", "PCI DSS requires defined and understood security testing processes."),
            _control("pci_dss", "PCI.11.3", "PCI DSS requires vulnerabilities to be identified, prioritized, and addressed."),
            _control("pci_dss", "PCI.11.4", "PCI DSS requires penetration testing to be performed regularly."),
            _control("iso27001", "ISO.A8.8", "ISO expects technical vulnerabilities to be managed through assessment and remediation."),
        ],
        tags=['security', 'vulnerability-management', 'penetration-testing', 'remediation'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_044",
        "Secure Software Development Lifecycle",
        "Is security embedded throughout the software development lifecycle, including secure coding, change management, and protection of payment or customer-facing pages?",
        "Look for secure SDLC standards, code review practices, vulnerability remediation in custom software, change control records, and integrity checks on public-facing scripts.",
        [
            _control("nist_csf", "NIST.PR.PS.06", "NIST expects secure software development practices to be integrated into the SDLC."),
            _control("pci_dss", "PCI.6.1", "PCI DSS requires defined and understood secure development processes."),
            _control("pci_dss", "PCI.6.2", "PCI DSS requires bespoke and custom software to be developed securely."),
            _control("pci_dss", "PCI.6.3", "PCI DSS requires security vulnerabilities to be identified and addressed."),
            _control("pci_dss", "PCI.6.4", "PCI DSS requires public-facing web applications to be protected against attacks."),
            _control("pci_dss", "PCI.6.5", "PCI DSS requires changes to system components to be managed securely."),
            _control("pci_dss", "PCI.6.6", "PCI DSS requires payment page scripts to be managed with integrity ensured."),
            _control("iso27001", "ISO.A8.25", "ISO expects a secure development life cycle to be defined and applied."),
            _control("iso27001", "ISO.A8.26", "ISO expects application security requirements to be defined in development."),
            _control("iso27001", "ISO.A8.27", "ISO expects secure system architecture and engineering principles to be applied."),
            _control("iso27001", "ISO.A8.28", "ISO expects secure coding practices to be followed in development."),
            _control("iso27001", "ISO.A8.29", "ISO expects security testing in development and acceptance."),
            _control("iso27001", "ISO.A8.31", "ISO expects separation of development, test, and production environments."),
            _control("iso27001", "ISO.A8.32", "ISO expects change management to control modifications to systems."),
            _control("iso27001", "ISO.A8.33", "ISO expects test information to be protected and managed."),
        ],
        tags=['security', 'secure-development', 'change-management', 'application-security'],
        criticality="high",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_045",
        "Physical Security Controls",
        "Are physical access controls in place to protect facilities, workstations, and media that hold sensitive or regulated data?",
        "Look for facility access control mechanisms, visitor management, workstation physical security, and monitoring of physical access to areas holding sensitive systems or media.",
        [
            _control("hipaa", "HIPAA.164.310a1", "HIPAA requires contingency operations procedures allowing facility access in support of restoration."),
            _control("hipaa", "HIPAA.164.310a2", "HIPAA requires facility access controls limiting physical access to ePHI systems."),
            _control("hipaa", "HIPAA.164.310a3", "HIPAA requires procedures to validate a person's authority for facility access."),
            _control("hipaa", "HIPAA.164.310a4", "HIPAA expects maintenance records for repairs affecting physical security."),
            _control("hipaa", "HIPAA.164.310b", "HIPAA requires policies governing workstation use."),
            _control("hipaa", "HIPAA.164.310c", "HIPAA requires physical safeguards for workstations accessing ePHI."),
            _control("nist_csf", "NIST.DE.CM.02", "NIST expects the physical environment to be monitored for potentially adverse events."),
            _control("pci_dss", "PCI.9.1", "PCI DSS requires defined and understood physical access controls."),
            _control("pci_dss", "PCI.9.2", "PCI DSS requires physical access controls to be maintained."),
            _control("pci_dss", "PCI.9.3", "PCI DSS requires physical access for personnel to be controlled and monitored."),
            _control("iso27001", "ISO.A7.1", "ISO expects physical security perimeters to protect information processing facilities."),
            _control("iso27001", "ISO.A7.2", "ISO expects physical entry controls to secure areas."),
            _control("iso27001", "ISO.A7.3", "ISO expects offices, rooms, and facilities to be secured."),
            _control("iso27001", "ISO.A7.4", "ISO expects physical security monitoring through surveillance."),
            _control("iso27001", "ISO.A7.5", "ISO expects protection against physical and environmental threats."),
            _control("iso27001", "ISO.A7.6", "ISO expects controls for working in secure areas."),
            _control("iso27001", "ISO.A7.7", "ISO expects clear desk and clear screen policies."),
            _control("iso27001", "ISO.A7.8", "ISO expects equipment to be sited and protected appropriately."),
            _control("iso27001", "ISO.A7.9", "ISO expects security of assets off-premises."),
            _control("iso27001", "ISO.A7.11", "ISO expects supporting utilities to protect information processing facilities."),
            _control("iso27001", "ISO.A7.12", "ISO expects cabling security to prevent interception or damage."),
            _control("iso27001", "ISO.A7.13", "ISO expects equipment maintenance to preserve availability and security."),
        ],
        tags=['security', 'physical-security', 'facility-access', 'workstation-security'],
        criticality="medium",
        domain_group="security",
    ),
    _cluster(
        "CLUSTER_046",
        "Continuous Threat Detection And Anomaly Analysis",
        "Does the organization continuously monitor for security events, detect anomalies, and correlate signals across network, endpoint, wireless, and external-service environments?",
        "Look for monitoring tooling coverage, alert correlation, anomaly baselines, wireless access point discovery, and evidence that detections lead to timely follow-up.",
        [
            _control("nist_csf", "NIST.DE.CM.01", "NIST expects networks to be monitored to find potentially adverse events."),
            _control("nist_csf", "NIST.DE.CM.06", "NIST expects external service provider activity to be monitored for adverse events."),
            _control("nist_csf", "NIST.DE.AE.02", "NIST expects potentially adverse events to be analyzed to characterize them."),
            _control("nist_csf", "NIST.DE.AE.03", "NIST expects event data to be correlated from multiple sources."),
            _control("nist_csf", "NIST.DE.AE.04", "NIST expects the estimated impact of events to be understood."),
            _control("nist_csf", "NIST.DE.AE.07", "NIST expects threat intelligence to be integrated into detection activities."),
            _control("nist_csf", "NIST.DE.AE.08", "NIST expects anomalies to be detected and the rationale documented."),
            _control("pci_dss", "PCI.11.2", "PCI DSS requires wireless access points to be identified and monitored."),
            _control("pci_dss", "PCI.11.5", "PCI DSS requires network intrusions and unexpected file changes to be detected and responded to."),
        ],
        tags=['incident_response', 'threat-detection', 'anomaly-detection', 'monitoring'],
        criticality="high",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_047",
        "Post-Incident Recovery And Communication",
        "Does the organization execute structured recovery from incidents, verify restoration, and communicate recovery status internally and externally as needed?",
        "Look for recovery plan execution records, verification steps confirming systems are fully restored, mission-function prioritization, and communications issued during and after recovery.",
        [
            _control("nist_csf", "NIST.RC.CO.03", "NIST expects recovery activities to be communicated to internal stakeholders."),
            _control("nist_csf", "NIST.RC.CO.04", "NIST expects public updates to be issued about recovery as appropriate."),
        ],
        tags=['incident_response', 'recovery', 'business-continuity', 'communications'],
        criticality="high",
        domain_group="incident_response",
    ),
    _cluster(
        "CLUSTER_048",
        "PHI Minimum Necessary And De-Identification",
        "Does the organization limit the use and disclosure of PHI to what is minimally necessary for each purpose and apply de-identification where appropriate?",
        "Look for minimum-necessary policies applied to routine disclosures, treatment/payment/operations handling rules, and de-identification methodology used to reduce re-identification risk.",
        [
            _control("hipaa", "HIPAA.164.502a", "HIPAA's minimum necessary standard governs routine PHI use and disclosure."),
            _control("hipaa", "HIPAA.164.502b", "HIPAA permits broader use for treatment, payment, and operations within defined limits."),
            _control("hipaa", "HIPAA.164.514a", "HIPAA defines de-identification standards that remove PHI from the Privacy Rule's reach."),
        ],
        tags=['data_protection', 'data-minimization', 'de-identification', 'phi-handling'],
        criticality="medium",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_049",
        "Accounting Of Disclosures And Restriction Rights",
        "Can the organization track and honor requests to restrict processing, account for disclosures, and accommodate confidential communication preferences?",
        "Look for a disclosure log or accounting mechanism, restriction request workflow, and confidential communication handling that is actually operational, not just policy text.",
        [
            _control("hipaa", "HIPAA.164.528", "HIPAA grants individuals the right to an accounting of certain disclosures of their PHI."),
            _control("hipaa", "HIPAA.164.522", "HIPAA grants individuals the right to request restrictions on uses and disclosures of PHI."),
            _control("hipaa", "HIPAA.164.522b", "HIPAA also grants the right to request confidential communications."),
        ],
        tags=['consent_rights', 'disclosure-accounting', 'restriction-rights', 'phi-handling'],
        criticality="medium",
        domain_group="consent_rights",
    ),
    _cluster(
        "CLUSTER_050",
        "Cardholder Data Scope And Storage Minimisation",
        "Has the organization defined and validated the scope of its cardholder data environment, and does it minimize stored account data while never retaining sensitive authentication data post-authorization?",
        "Look for CDE scoping documentation, data flow validation, storage minimization rules, and explicit controls preventing retention of full track data, CVV, or PIN data after authorization.",
        [
            _control("pci_dss", "PCI.3.1", "PCI DSS requires defined and understood account data protection processes."),
            _control("pci_dss", "PCI.3.2", "PCI DSS requires storage of account data to be kept to a minimum."),
            _control("pci_dss", "PCI.3.3", "PCI DSS prohibits storage of sensitive authentication data after authorization."),
            _control("pci_dss", "PCI.3.4", "PCI DSS requires access to displays of the full PAN to be restricted."),
            _control("pci_dss", "PCI.12.5", "PCI DSS requires the CDE scope to be documented and validated."),
        ],
        tags=['data_protection', 'cardholder-data', 'data-minimization', 'pci-scope'],
        criticality="critical",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_051",
        "Organizational Context And Mission Alignment",
        "Does the organization understand its mission, stakeholders, and priorities well enough to direct cybersecurity risk management decisions, and is that direction reviewed for effectiveness?",
        "Look for documented organizational mission and context statements, identification of internal and external stakeholders, stated outcomes and priorities, and periodic review of whether risk management performance supports those priorities.",
        [
            _control("nist_csf", "NIST.GV.OC.01", "NIST expects the organizational mission to be understood and used to inform cybersecurity risk management."),
            _control("nist_csf", "NIST.GV.OC.02", "NIST expects internal and external stakeholders to be identified and their needs understood."),
            _control("nist_csf", "NIST.GV.OC.05", "NIST expects outcomes and priorities to inform cybersecurity risk management decisions."),
            _control("nist_csf", "NIST.GV.OV.02", "NIST expects risk management performance to be evaluated and reviewed."),
            _control("nist_csf", "NIST.GV.OV.03", "NIST expects organizational risk management adjustments to be made based on review outcomes."),
        ],
        tags=['governance', 'organizational-context', 'mission-alignment', 'risk-oversight'],
        criticality="medium",
        domain_group="governance",
    ),
    _cluster(
        "CLUSTER_052",
        "Data Minimization At Collection",
        "Does the organization limit collection of personal data to what is necessary for the stated purpose, applying minimization principles at the point of data gathering?",
        "Look for data minimization policies, collection justification documentation, and evidence that data fields are reviewed for necessity before collection. Check whether the organization can demonstrate that excessive or irrelevant data is not being collected.",
        [
            _control("dpdpa", "CH2.MINIMIZE.1", "DPDPA Section 8 requires collection to be limited to data that is necessary for the stated purpose."),
            _control("gdpr", "GDPR.ART5C.1", "GDPR Article 5(1)(c) treats data minimization as a core processing principle."),
        ],
        tags=['data_protection', 'data-minimization', 'data-collection', 'privacy-by-design'],
        criticality="high",
        domain_group="data_protection",
    ),
    _cluster(
        "CLUSTER_053",
        "Purpose Limitation And Lawful Basis Documentation",
        "Does the organization ensure personal data is processed only for the purpose for which consent was obtained or a legitimate use applies, and document all legitimate-use cases?",
        "Look for purpose-limitation policies, a register of legitimate-use cases under the relevant lawful basis, compatibility assessments for secondary uses, and evidence that processing outside the stated purpose is prevented or justified.",
        [
            _control("dpdpa", "CH2.PURPOSE.1", "DPDPA Section 6 limits processing to the purpose for which consent was obtained."),
            _control("dpdpa", "CH2.PURPOSE.2", "DPDPA Section 7 requires legitimate uses to be identified and documented when processing without consent."),
            _control("gdpr", "GDPR.ART6.3", "GDPR Article 6(1)(f) requires a legitimate-interest assessment balancing controller interests against data subject rights."),
            _control("gdpr", "GDPR.ART6.4", "GDPR requires compatibility assessment when processing for a new purpose beyond the original collection."),
        ],
        tags=['consent_rights', 'purpose-limitation', 'lawful-basis', 'legitimate-interest'],
        criticality="high",
        domain_group="consent_rights",
    ),

]

# ── Intentional singletons ────────────────────────────────────────
# Controls deliberately left un-clustered: they surface as one-off singleton
# questions in multi-framework assessments because they have no genuine
# cross-framework overlap. Every framework control must be a member of
# exactly one cluster above OR listed here — enforced by
# tests/test_content_integrity.py. Adding a control here is a reviewed
# decision, not a default.

INTENTIONAL_SINGLETONS: dict[str, set[str]] = {
    "dpdpa": set(),
    "iso27001": {"ISO.A5.32"},
    "gdpr": {"GDPR.ART27.1", "GDPR.ART9.1"},
    "hipaa": set(),
    "nist_csf": set(),
    "pci_dss": set(),
}
